### PR TITLE
Harden the selected feature check in the multi feature list model

### LINKED ISSUE #3127: Issue checkboxes contents not well displayed / crash the application
Hello, 

Since one of the last updates, I noticed an issue with the checkboxes we use to select entities in the feature list. 

When several entities are selected, some errors occurs, or bad display. 
- After the action, "moving", the entities aren't visually ticked anymore, but they are. 
- After the action delete, if 2 entities are selected, only one is deleted. No more actions are proposed in the (except toggle feature selection) ; which means Qfield consider nothing is selected (the remaining entity is still existing and still ticked) 
- Duplicate crash the application

It was working well before one of the lasts updates. 

Here is a video of the error with the action "moving". 

https://user-images.githubusercontent.com/72577399/181289049-6afe1d58-c1e5-49b9-99c8-0ab193617c9c.mp4

Desktop

OS: [Windows 10] 
QGIS Version [3.26.0]
QFieldSync Version [4.1.1]

Mobile

Device: [Samsung Galaxy S9]
OS: [Android 11]
QField version: [master-dev (c77752)]

Additional information

    Problem started happening recently, didn't happen in an older version of QField: [Yes]
    Problem can be reliably reproduced, doesn't happen randomly: [Yes]
    Problem happens with all files and projects, not only some files or projects: [Yes]

### PR DESCRIPTION
**Pull request by nirvn**
Consider checked features with same vector layer and feature ID to avoid out of sync feature details between selected and all feature lists.

Fixes #3127.

### CODE REVIEW

**Review by suricactus — APPROVED** [review]

File: src/core/multifeaturelistmodelbase.cpp [hunk 1]
```diff
@@ -223,7 +223,15 @@ QVariant MultiFeatureListModelBase::data( const QModelIndex &index, int role ) c
       return feature->second.id();
 
     case MultiFeatureListModel::FeatureSelectedRole:
-      return mSelectedFeatures.contains( mFeatures.at( index.row() ) );
+      for( auto &pair : mSelectedFeatures )
```
Comment (suricactus) [inline src/core/multifeaturelistmodelbase.cpp:226]:
```suggestion
      for ( auto &pair : mSelectedFeatures )
```

File: src/core/multifeaturelistmodelbase.cpp [hunk 2]
```diff
@@ -223,7 +223,15 @@ QVariant MultiFeatureListModelBase::data( const QModelIndex &index, int role ) c
       return feature->second.id();
 
     case MultiFeatureListModel::FeatureSelectedRole:
-      return mSelectedFeatures.contains( mFeatures.at( index.row() ) );
+      for ( auto &pair : mSelectedFeatures )
```
Comment (m-kuhn) [inline src/core/multifeaturelistmodelbase.cpp:226]:
```suggestion
      for ( const auto &pair : mSelectedFeatures )
```

File: src/core/multifeaturelistmodelbase.cpp [hunk 3]
```diff
@@ -509,10 +517,9 @@ bool MultiFeatureListModelBase::duplicateSelection()
 
 bool MultiFeatureListModelBase::moveSelection( const double x, const double y )
 {
-  if ( !canDuplicateSelection() )
+  if ( !canMoveSelection() )
```
Comment (m-kuhn) [inline src/core/multifeaturelistmodelbase.cpp:520]: Good catch

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5ce4fc81718acdb584af2cadda65ee6219535df1: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3136-96d46e0e66101b3626ed1383d7b815e8e93fa678-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3136-96d46e0e66101b3626ed1383d7b815e8e93fa678-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3136-96d46e0e66101b3626ed1383d7b815e8e93fa678-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3136-96d46e0e66101b3626ed1383d7b815e8e93fa678-x86-android.apk)
</details>
