### PR TITLE
Fix QField crashing on exit (fixes #1505)

### LINKED ISSUE #1505: Crash on closing
Crash on closing.

### Reproduction Steps:

Press back twice to close qfield and app crashes.

**QField version:** [1.8.0 ()]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

### PR DESCRIPTION
**Pull request by nirvn**
Introduced in 1.8.0, we were destroying a destroyed QBluetoothSocket.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3c80f2120e4025e0fc3a271bed17c24e020567b2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-ead2c906e396f4d05e8391df80324133cbe07a07-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-ead2c906e396f4d05e8391df80324133cbe07a07-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-ead2c906e396f4d05e8391df80324133cbe07a07-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-ead2c906e396f4d05e8391df80324133cbe07a07-x86.apk)

File: src/core/bluetoothreceiver.cpp [hunk 1]
```diff
@@ -40,6 +40,12 @@ BluetoothReceiver::BluetoothReceiver( QObject *parent ) : QObject( parent ),
   }
 }
 
+BluetoothReceiver::~BluetoothReceiver()
+{
+  mSocket.release(); // deleted by QgsGpsConnection::cleanupSource
```
Comment (m-kuhn) [inline src/core/bluetoothreceiver.cpp:45]: Could we use a raw pointer instead of a unique_ptr?
If we don't hand over ownership, we shouldn't be using unique_ptr?

Comment (nirvn) [reply src/core/bluetoothreceiver.cpp:45]: That'd be perfectly fine yes

Comment (nirvn) [reply src/core/bluetoothreceiver.cpp]: @m-kuhn , done.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f22e6b4f155f98d4b27c20a45cf4fa08c4e77aea:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-f27a8f411125af2fbfc65ca12047277810b1c70b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-f27a8f411125af2fbfc65ca12047277810b1c70b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-f27a8f411125af2fbfc65ca12047277810b1c70b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-f27a8f411125af2fbfc65ca12047277810b1c70b-x86.apk)

File: src/core/bluetoothreceiver.cpp [hunk 2]
```diff
@@ -40,6 +40,11 @@ BluetoothReceiver::BluetoothReceiver( QObject *parent ) : QObject( parent ),
   }
 }
 
+BluetoothReceiver::~BluetoothReceiver()
+{
```
Comment (m-kuhn) [inline src/core/bluetoothreceiver.cpp:44]: Isn't that done implicitly? I.e. we can just remove the dtor?

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1fc476e8e3012f7cd1d7de2ddd51de48eac28072:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-85e00548aeeada2c282be147756b298ad2103ffb-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-85e00548aeeada2c282be147756b298ad2103ffb-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-85e00548aeeada2c282be147756b298ad2103ffb-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1554-85e00548aeeada2c282be147756b298ad2103ffb-x86.apk)
