### PR TITLE
Fix USB copying photos captured by QField Android in a project subfolder created during capture

### LINKED ISSUE #3736: Problem with uploading photos in DCIM folder created by QField
### Describe the issue
If a QField project starts with no DCIM folder, but creates one due to user taking a picture, other apps (Autosync & Cx File Explorer) can't access its contents

### Reproduction steps
1. Create a project with the capacity to take pictures but no DCIM folder
2. Export it to QField
3. Take a picture
4. Try to look at the contents of the DCIM folder with Cx File Explorer (after of course getting permission to look at the contents of ch.opengis.qfield), and find that you can't (or try to set up an Autosync upload to cloud, but that is more complex)
5. Delete the DCIM folder and create a new one with Cx File
6. Take another picture
7.  Find that viewing and Autosync upload now works.

### Expected behavior
Contents of folders created by QField ought to be accessible by other apps

### Observed behavior
they aren't

### Desktop (please complete the following information)
 - OS: W10
 - QGIS Version: 3.26.3
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Pixel 6 Pro
 - OS:  Android 13
 - QField version: 2.5.6 13f23d v2.5.6

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Not as far as I know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: All the ones I've tried (several)

### PR DESCRIPTION
**Pull request by nirvn**
This PR fixes #3736 and #3799 , whereas photos captured in QField Android with an expression that would create a folder not present during the initial project import would fail to copy via USB cable.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 60be141dd5aadd182bd31cfb50b1e4d64b76a90c: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3818-6fece325f9d50835d8703619df5dbcfbff92a64b-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3818-6fece325f9d50835d8703619df5dbcfbff92a64b-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3818-6fece325f9d50835d8703619df5dbcfbff92a64b-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3818-6fece325f9d50835d8703619df5dbcfbff92a64b-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3818-6fece325f9d50835d8703619df5dbcfbff92a64b-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3818-6fece325f9d50835d8703619df5dbcfbff92a64b-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3818-6fece325f9d50835d8703619df5dbcfbff92a64b-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3818-6fece325f9d50835d8703619df5dbcfbff92a64b-x86-android.apk)
</details>

File: src/core/platforms/android/androidplatformutilities.cpp [hunk 1]
```diff
@@ -345,6 +346,10 @@ PictureSource *AndroidPlatformUtilities::getCameraPicture( QQuickItem *parent, c
   if ( !checkCameraPermissions() )
     return nullptr;
 
+  const QFileInfo destinationInfo( prefix + pictureFilePath );
+  const QDir prefixDir( prefix );
+  prefixDir.mkpath( destinationInfo.absolutePath() );
```
Comment (suricactus) [inline src/core/platforms/android/androidplatformutilities.cpp:351]: Probably a good idea to check whether the `mkpath` returned true?

**Review by suricactus — APPROVED** [review]
Much cleaner code! I like it!

File: src/core/platforms/android/androidplatformutilities.cpp (hunk 1 above)
Comment (nirvn) [reply src/core/platforms/android/androidplatformutilities.cpp:351]: I'll take a note of it here and think of how we can address that in a better way. On that front the old code also assumed the mkdirs() would always work. I think we'll need some handling on the QML side too.

In any case, I'd like to keep this limited to moving the mkdirs to a mkpath for now and bring the fix to 2.6.
