### PR TITLE
fix: if a feature is deleted and the undo-ed, do not store any `delete` or `create` delta

### LINKED ISSUE #6583: Unexpected behavior on undo delete operation
### What is the bug or the crash? What were your expectations and what actually happened?

Undoing an unpushed delete operation unexpectedly creates both a delete delta and an insert delta, instead of creating no delta at all.

This causes problems when using database layers because some fields may be autogenerated when the feature is re-inserted, creating a completely new feature. For example, in our case a new uuid is generated, which then messes up the version info for the feature.

### Steps to reproduce the issue

1. Delete a feature
2. Undo the delete operation
3. Push changes
4. Notice that two deltas are created, even though no actual changes were made

### Version

3.7.3

### Operating system name

Android

### Operating system version

15

### Reinstall QField

- [ ] I have a fresh install of the latest QField version, but the problem persists.
- [x] Problem can be reliably reproduced, doesn't happen randomly.
- [x] Problem happens with all files and projects, not only some files or projects.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by suricactus**
In this PR I took the opportunity to:

- align the naming to use `existingDelta` when merging deltas
- in `mLocalPkToDeltaUuid` store all local deltas, not only the "create"
- this lead to simplifying the merge of patch deltas
- if a feature is deleted and the undo-ed, do not store any `delete` or `create` delta

Prior to this commit, undoing an unpushed delete operation unexpectedly
creates both a "delete" and a "create" delta, instead of creating no
delta at all.

This scenario tested and confirms the following scenarios work well:

```
0. existing feature f1
1. modify f1 -> added `patch` delta
2. modify f1 -> updated `patch` delta
3. delete f1 -> added `delete` delta
4. undo -> removed `delete` delta
5. undo -> restore `patch` to it's state in 1)
6. undo -> removed `patch` delta
7. redo -> restore `patch` to it's state in 1)
8. redo -> restore `patch` to it's state in 2)
9. redo -> restore `delete` to it's state in 3)

1. create f1 -> added `create` delta
2. undo -> removed `create` delta
3. redo -> added `create` delta

1. create f1 -> added `create` delta
2. modify f1 -> updated `create` delta
3. undo -> restored `create` delta to it's state in 1)
4. redo -> restored `create` delta to it's state in 2)
5. undo -> restored `create` delta to it's state in 1)

1. create f1 -> added `create` delta
2. delete f1 -> removed `create` delta
3. undo -> added `create` delta to it's state in 1)
4. redo -> removed `create` delta

1. create f1 -> added `create` delta
2. modify f1 -> updated `create` delta
3. delete f1 -> removed `create` delta
4. undo -> restored `create` delta to it's state in 3)
5. undo -> restored `create` delta to it's state in 2)
6. undo -> removed `create` delta
7. redo -> restored `create` delta to it's state in 2)
```

Fix #6583

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-6588 fix: undoing an unpushed delete operation unexpectedly creates both a delete delta and an insert delta](https://app.clickup.com/t/2192114/QF-6588)

File: src/core/deltafilewrapper.cpp [hunk 1]
```diff
@@ -830,14 +830,52 @@ void DeltaFileWrapper::mergeCreateDelta( const QJsonObject &delta )
...
+        mDeltas.removeAt( existingDeltaIdx );
+        mIsDirty = true;
+
+        emit countChanged();
+
+        qInfo() << "DeltaFileWrapper::mergeCreateDelta: removed delete delta instead of adding a create delta: " << existingDeltaIdx;
+
+        return;
+      }
+    }
```
Comment (nirvn) [inline src/core/deltafilewrapper.cpp:869]: The logic sounds good, could we get it tested in test_deltafilewrapper.cpp ?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 45fa654bf97e52920aaf4213865a2b19d30bd25e: [**arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-6606-7dcc388669e01068ae4a06b086a7054e5c9fd5bb-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-6606-7dcc388669e01068ae4a06b086a7054e5c9fd5bb-android-arm-neon.apk)
- [x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-6606-7dcc388669e01068ae4a06b086a7054e5c9fd5bb-android-x64.apk)
- [x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-6606-7dcc388669e01068ae4a06b086a7054e5c9fd5bb-android-x86.apk)
- [**all access arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-6606-7dcc388669e01068ae4a06b086a7054e5c9fd5bb-android-arm64.apk)
- [all access arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-6606-7dcc388669e01068ae4a06b086a7054e5c9fd5bb-android-arm-neon.apk)
- [all access x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-6606-7dcc388669e01068ae4a06b086a7054e5c9fd5bb-android-x64.apk)
- [all access x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-6606-7dcc388669e01068ae4a06b086a7054e5c9fd5bb-android-x86.apk)
</details>

File: src/core/deltafilewrapper.cpp (hunk 1 above)
Comment (suricactus) [reply src/core/deltafilewrapper.cpp:869]: I wanted to get it tested too, but I will not have the time to write the tests myself for now. Actually we have the two new functions from my recent PRs are also a very good candidates.

Is it acceptable to merge without a test for you?

**Comment by duke-nyuki** [comment]
Task linked: [QF-6589 Prevent deltas with sourcePk having value 0](https://app.clickup.com/t/2192114/QF-6589)

**Comment by nirvn** [comment]
@suricactus , all good, can you resolve the conflict?

**Review by nirvn — APPROVED** [review]

**Comment by suricactus** [comment]
Yes, I was waiting for the base branch to merge.

**Comment by nirvn** [comment]
@suricactus , thanks for the rebase, merging.

**Comment by qfield-fairy** [comment]
The backport to `release-3_7` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply fac4a721b... fix: if a feature is modified and then deleted, keep only the "delete" delta
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/core/deltafilewrapper.cpp
CONFLICT (content): Merge conflict in src/core/deltafilewrapper.cpp
Auto-merging src/core/deltafilewrapper.h

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release-3_7 release-3_7
# Navigate to the new working tree
cd .worktrees/backport-release-3_7
# Create a new branch
git switch --create backport-6606-to-release-3_7
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick fac4a721b33f2a354de47d3019e4d07524d65ac3,45fa654bf97e52920aaf4213865a2b19d30bd25e
# Push it to GitHub
git push --set-upstream origin backport-6606-to-release-3_7
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release-3_7
```
Then, create a pull request where the `base` branch is `release-3_7` and the `compare`/`head` branch is `backport-6606-to-release-3_7`.
